image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python310"
      PLATFORM: x86
    - PYTHON: "C:\\Python310-x64"
      PLATFORM: x64

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - '%PYTHON%\python.exe --version'
  - '%PYTHON%\python.exe -m pip install --upgrade pip setuptools wheel'
  - '%PYTHON%\python.exe -m pip install --force-reinstall pyinstaller'
  - '%PYTHON%\python.exe -m pip show pyinstaller'
  - pyinstaller --version

build_script:
  - pyinstaller --onefile --noconsole --name ExcelSplitter-%PLATFORM% excel-splitter.py

artifacts:
  - path: dist\*.exe
    name: ExcelSplitter
