image: Visual Studio 2019

environment:
  matrix:
    - PLATFORM: x86
    - PLATFORM: x64

init:
  - cmd: python -m pip install --upgrade pip setuptools wheel

build_script:
  - set PLATFORM=%PLATFORM%
  - pip install -r requirements.txt
  - pyinstaller --onefile --noconsole --name ExcelSplitter-%PLATFORM% excel-splitter.py

artifacts:
  - path: dist\*.exe
    name: ExcelSplitter