image: Visual Studio 2019

environment:
  matrix:
    - PLATFORM: x86
    - PLATFORM: x64

install:
  - choco install python --version=3.10.9
  - refreshenv
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install pyinstaller

build_script:
  - set PLATFORM=%PLATFORM%
  - python -m pyinstaller --onefile --noconsole --name ExcelSplitter-%PLATFORM% excel-splitter.py

artifacts:
  - path: dist\*.exe
    name: ExcelSplitter